apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-app
  template:
    metadata: 
      labels:
        app: provider-app
    spec:
      containers:
        - name: provider-app
          image: provider:v10
          ports:
            - containerPort: 3001